### ISSUE TITLE
Success Ranking Screen

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#22]
It's just a view

<img width="291" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdy9TQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--623668caf0f234b9540b02aa51ee2cb0fdf0e9ee/image.png" alt="image.png" />

**Comment by MoeNick** [comment]
What's the status of this @mmahdigh @jainkrati ?
I checked with @alireza-sharifpour and he said it's not implemented.

**Comment by alireza-sharifpour** [comment]
It's ready for testing @maryjaf

**Comment by maryjaf** [comment]
> It's ready for testing @maryjaf

Since the status remains "Ranking" until the vote be submitted, in this page the "ranking" status is shown 
in figme it's shown "ranked" but I think the right status is "ranking", am I right? @MoeNick @alireza-sharifpour 


![msg55484320-403475](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/26b0fcb7-8ddc-4b72-accf-9bc7960c8c81)
